TILEWIDTH = 16
TILEHEIGHT = 16
NROWS = 36
NCOLS = 28
SCREENWIDTH = NCOLS * TILEWIDTH
SCREENHEIGHT = NROWS * TILEHEIGHT
SCREENSIZE = (SCREENWIDTH, SCREENHEIGHT)

BLACK = (0, 0, 0)
YELLOW = (255, 255, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
PINK = (255,100,150)
TEAL = (100,255,255)
ORANGE = (230,190,40)

STOP = 0
UP = 1
DOWN = -1
LEFT = 2
RIGHT = -2
PORTAL = 3


PACMAN = 0
PELLET = 1
POWERPELLET = 2
GHOST = 3
BLINKY = 4
PINKY = 5
INKY = 6
CLYDE = 7
FRUIT = 8

SCATTER = 0
CHASE = 1
FREIGHT = 2
SPAWN = 3

SCORETXT = 0
LEVELTXT = 1
READYTXT = 2
PAUSETXT = 3
GAMEOVERTXT = 4


HUNT_GHOSTS= "Huns Ghosts"
EAT_PELLETS = "Eat Pellets"

FOLLOW_PATH_TO_SUPERPELLET = "Follow Path to Superpellet"
GO_TO_TARGET_QUADRANT = "Go To Target Quadrant"
VISIT_NEW_QUADRANT = "Visit New Quadrant"
WANDER = "Wander"
GO_CLOSE_CORNER = "Go Close Corner"
GO_TO_FRUIT = "Go To Fruit"
DUMMY = "Dummy"

TOP_LEFT = 1
TOP_RIGHT = 2
BOT_LEFT = -2
BOT_RIGHT = -1